import { useEffect, useState } from 'react';
import { questions, skills, subjects, topicById, skillById } from '../data/catalog';
import { advanceReview, beginReview, reviewSummary, selectReview, showReviewQuestion, type ReviewSize } from '../domain/adaptive';
import type { AdaptiveSession, SubjectId } from '../domain/types';
import { useStudy } from '../state/StudyProvider';
import { AnswerBox } from '../components/Quiz';
import { Badge, Button, Heading, Panel, ProgressBar } from '../components/ui';

export function AdaptiveReviewPage({ go }: { go: (page: string) => void }) {
  const { state, mutate, storageError } = useStudy();
  const [size, setSize] = useState<ReviewSize>(15), [subject, setSubject] = useState<SubjectId | 'all'>('all');
  const [activeId, setActiveId] = useState<string | undefined>(() => state.adaptive.sessions.filter(s => !s.completedAt).at(-1)?.id);
  const session = state.adaptive.sessions.find(s => s.id === activeId), item = session?.items[session.index];
  useEffect(() => { if (session && !session.completedAt && !item?.shownAt) mutate(previous => showReviewQuestion(previous, session.id)); }, [session?.id, session?.index, session?.completedAt]);
  const plan = selectReview(state, questions, skills, size, { subject });
  const label = <Heading eyebrow="ВСПОМНИТЬ И ЗАКРЕПИТЬ" title="Повторение на сегодня" subtitle="Подборка из изученных тем — с учётом ошибок и давности повторения."/>;
  if (!session) return <>{label}<Panel><div className="adaptive-controls"><label>Размер занятия<select aria-label="Размер занятия" value={size} onChange={e => setSize(Number(e.target.value) as ReviewSize)}>{[5,10,15,20].map(n => <option key={n} value={n}>{n} вопросов</option>)}</select></label><label>Предмет<select aria-label="Предмет повторения" value={subject} onChange={e => setSubject(e.target.value as SubjectId | 'all')}><option value="all">Все предметы</option>{subjects.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}</select></label></div><p className="muted">Доступно заданий: {plan.available}. Новые неизученные темы не включаются. Учитываются и необходимые базовые темы.</p>{plan.available > 0 && plan.items.length < size && <p className="callout">Доступно только {plan.items.length} разных заданий. Занятие будет короче: {plan.items.length} вместо {size}. Неизученные темы не добавляем.</p>}{!plan.available ? <p className="callout">Для этой подборки пока нет изученного материала. Открой предмет и отметь знакомую тему или реши её задания.</p> : <Button disabled={!!storageError} onClick={() => { const id = crypto.randomUUID(); mutate(previous => beginReview(previous, plan.items, size, subject, id)); setActiveId(id); }}>Начать повторение</Button>}</Panel>{state.adaptive.sessions.length > 0 && <Panel><h2>Мои занятия</h2><div className="adaptive-history">{[...state.adaptive.sessions].reverse().slice(0,10).map(s => <Button key={s.id} variant="outline" onClick={() => setActiveId(s.id)}>{new Date(s.startedAt).toLocaleDateString('ru-RU')} · {s.items.length} вопросов · {s.completedAt ? 'Итог' : 'Продолжить'}</Button>)}</div></Panel>}<Button variant="ghost" onClick={() => go('review')}>К плану повторений</Button></>;
  if (session.completedAt) return <>{label}<SessionResult session={session}/><div className="button-row"><Button onClick={() => setActiveId(undefined)}>Новое занятие</Button><Button variant="outline" onClick={() => go('errors')}>Мои ошибки</Button></div></>;
  if (!item) return null;
  const lastAttempt = state.attempts.find(a => a.id === item.attemptIds.at(-1));
  return <>{label}<Panel className="quiz-panel"><div className="section-heading"><div><span className="eyebrow">АВТОМАТИЧЕСКОЕ ПОВТОРЕНИЕ</span><h2>{topicById[item.question.topic]?.title ?? item.question.topic}</h2><p className="small muted">{subjects.find(s => s.id === item.question.subject)?.short}</p></div><Badge>{session.index + 1} / {session.items.length}</Badge></div><ProgressBar value={session.index / session.items.length * 100} label="Прогресс повторения"/><details className="priority-details"><summary>Почему это задание?</summary><p>Приоритет: {item.score}</p><ul>{item.reasons.map(r => <li key={r.code}>{r.label}: {r.points > 0 ? '+' : ''}{r.points}</li>)}</ul></details><AnswerBox key={session.id + ':' + session.index} question={item.question} context="adaptive" adaptiveSessionId={session.id} initial={{ answer: lastAttempt?.answer ?? '', result: item.correct }}/>{item.correct !== null && <div className="quiz-next"><Button onClick={() => mutate(previous => advanceReview(previous, session.id))}>{session.index === session.items.length - 1 ? 'Завершить занятие' : 'Дальше'}</Button></div>}</Panel><Button variant="ghost" onClick={() => setActiveId(undefined)}>К выбору занятия</Button></>;
}
function SessionResult({ session }: { session: AdaptiveSession }) {
  const { state } = useStudy(), result = reviewSummary(session, state, questions);
  const table = (title: string, rows: typeof result.topics, names: (id: string) => string) => <section><h3>{title}</h3><div className="adaptive-breakdown">{rows.map(row => <div key={row.id}><span>{names(row.id)}</span><b>{row.correct} / {row.total}</b></div>)}</div></section>;
  const revisit = [...result.topics.filter(row => row.wrong || row.persistent).map(row => ({...row,title:topicById[row.id]?.title ?? row.id})), ...result.skills.filter(row => row.persistent).map(row => ({...row,title:skillById[row.id]?.title ?? row.id}))];
  return <><Panel className="adaptive-result"><h2>Занятие завершено</h2><p className="result-score">{result.correct} / {result.total}</p><p className="muted">Результат по первым ответам. Исправлено после новой попытки: {result.corrected}. Все попытки остались в истории.</p>{table('По предметам',result.subjects,id => subjects.find(s => s.id === id)?.short ?? id)}{table('По темам',result.topics,id => topicById[id]?.title ?? id)}{result.skills.length > 0 && table('По навыкам',result.skills,id => skillById[id]?.title ?? id)}</Panel><Panel><h2>Стоит повторить</h2>{revisit.length ? <ul className="revisit-list">{revisit.map(row => <li key={row.id}><b>{row.title}</b><span>{row.persistent ? 'В истории есть несколько независимых ошибок. Полезно вернуться к базовому шагу.' : row.wrong === 1 ? 'Одна ошибка в этом занятии. Это ещё не признак устойчивой слабости.' : `Ошибок в этом занятии: ${row.wrong}. Пока недостаточно данных об устойчивой слабости.`}</span></li>)}</ul> : <p className="muted">В этом занятии ошибок не было. Уверенные темы будут возвращаться для поддерживающего повторения.</p>}</Panel></>;
}
