import { subjects, topicById, topics } from '../data/catalog';
import { addDays, localDate, stats } from '../domain/progress';
import { useStudy } from '../state/StudyProvider';
import { Badge, Button, Icon } from '../components/ui';
import { FunctionPlot } from '../components/GraphLab';

export function StatsCards({ progress = false }: { progress?: boolean }) {
  const { state } = useStudy(), values = stats(state);
  return <div className="stats-grid">{[['Тем начато', values.started], ['Уверенно', values.mastered], ['Пора повторить', values.due], ['Задач решено', values.solved], [progress ? 'Ошибочных попыток' : 'Ошибок в ответах', values.errors], ['Дней подряд', values.streak]].map(([label, value]) => <div className="stat-card" key={label}><strong>{value}</strong><span>{label}</span></div>)}</div>;
}
export function Dashboard({ go }: { go: (page: string) => void }) {
  const { state } = useStudy(), next = topicById[state.settings.lastTopic ?? 'functions'] ?? topicById.functions;
  const subject = subjects.find(s => s.id === next.subject)!;
  const dueTopics = topics.filter(t => state.topics[t.id]?.status === 'Повторить' || (state.reviews[`topic:${t.id}`]?.due ?? '9999') <= localDate());
  const errors = state.errors.filter(e => e.status !== 'закрепил');
  const activityDays = new Set(state.activity.map(a => a.date));
  return <><div className="dashboard-heading"><div><span className="eyebrow">ТВОЁ ПРОСТРАНСТВО ДЛЯ УЧЁБЫ</span><h1>Привет, Radisonbe <span className="greeting-dot">✦</span></h1><p>Что разберём сегодня?</p></div><div className="date-pill"><Icon name="calendar" size={17}/>{new Date().toLocaleDateString('ru-RU', { day: 'numeric', month: 'long' })}</div></div><StatsCards/><div className="dashboard-columns"><div className="dashboard-primary"><section className="next-lesson"><div className="next-copy"><span className="eyebrow">{state.settings.lastTopic ? 'ПРОДОЛЖИТЬ ОБУЧЕНИЕ' : 'ХОРОШЕЕ МЕСТО ДЛЯ СТАРТА'}</span><Badge tone="teal">{subject.short}</Badge><h2>{next.title}{!state.settings.lastTopic && <><br/><span>От правила к графику</span></>}</h2><p>{state.settings.lastTopic ? 'Вернись к объяснению, заметкам и самостоятельной практике.' : next.description}</p><Button onClick={() => go(`topic/${next.id}`)}>{state.settings.lastTopic ? 'Продолжить тему' : 'Начать изучение'}<Icon name="arrow"/></Button><span className="next-time"><Icon name="clock" size={14}/>{next.minutes ?? 'В своём темпе'}{next.minutes ? ' минут · в своём темпе' : ''}</span></div><div className="next-visual">{next.id === 'functions' ? <><span className="formula-chip">f(x) = x²</span><FunctionPlot mini/><span className="graph-caption">Вход → правило → выход</span></> : <div className="next-symbol">{subject.symbol}<span className="graph-caption">Один понятный шаг</span></div>}</div></section><div className="section-heading subject-heading"><h2>Мои предметы</h2><span className="muted">Понимание важнее скорости</span></div><div className="subject-cards">{subjects.map(item => {
    const all = topics.filter(t => t.subject === item.id), mastered = all.filter(t => state.topics[t.id]?.status === 'Уверенно').length;
    return <button type="button" className="subject-card" key={item.id} onClick={() => go(item.id)}><div className="subject-card-top"><span className={`subject-symbol ${item.tone}`}>{item.symbol}</span><Icon name="arrow"/></div><h3>{item.title}</h3><p>{item.description}</p><div className="subject-card-bottom"><span>{all.filter(t => t.materialStatus === 'ready').length} {item.id === 'python' ? 'коротких уроков' : 'готовых модуля'}</span><span>{mastered}/{all.length} освоено</span></div><div className="thin-progress"><i style={{ width: `${mastered / all.length * 100}%` }}/></div></button>;
  })}</div></div><aside className="dashboard-aside"><section className="panel session-card"><span className="session-icon"><Icon name="clock" size={24}/></span><span className="eyebrow">НЕБОЛЬШОЕ ЗАНЯТИЕ</span><h2>15 минут для себя</h2><p>Повторение, три задания<br/>и одна разобранная ошибка.</p><Button onClick={() => go('session')}>У меня есть 15 минут <Icon name="arrow"/></Button></section><section className="today-panel panel"><div className="section-heading"><h3>Сегодня стоит<br/>повторить</h3><Icon name="review"/></div>{dueTopics.length ? dueTopics.slice(0, 3).map(t => <button className="today-link" key={t.id} onClick={() => go(`topic/${t.id}`)}>{t.title}<Icon name="arrow" size={15}/></button>) : <div className="today-empty"><b>Пока нет тем на сегодня</b><p>После первого занятия<br/>здесь появится твой план.</p></div>}{errors.length > 0 && <button className="today-link" onClick={() => go('errors')}>Ошибок к повторению: {errors.length}<Icon name="arrow" size={15}/></button>}<Button variant="ghost" onClick={() => go('review')}>Весь план повторений <Icon name="arrow" size={15}/></Button></section><section className="rhythm-panel panel"><div className="section-heading"><h3>Учебный ритм</h3><Icon name="progress"/></div><div className="rhythm-week">{Array.from({ length: 7 }, (_, i) => addDays(i - 6)).map(date => <div key={date} className={activityDays.has(date) ? 'active-day' : ''}><span>{new Date(date + 'T12:00:00').toLocaleDateString('ru-RU', { weekday: 'short' })}</span><b>{date.slice(-2)}</b></div>)}</div><p>{activityDays.size ? 'Каждый небольшой шаг складывается в твой путь.' : 'Первый учебный день начинается с маленького шага.'}</p></section></aside></div><div className="section-heading tools-heading"><h2>Твоя учебная система</h2></div><div className="tool-cards">{[{ id: 'errors', title: 'Мои ошибки', text: 'Понять причину и закрепить правило', count: `${errors.length} к разбору`, icon: 'errors' as const }, { id: 'review', title: 'Повторение', text: 'Вернуться к важному в нужный момент', count: `${dueTopics.length} на сегодня`, icon: 'review' as const }, { id: 'progress', title: 'Прогресс', text: 'Увидеть, как складываются твои шаги', count: `${stats(state).mastered} тем освоено`, icon: 'progress' as const }].map(item => <button className="tool-card" key={item.id} onClick={() => go(item.id)}><Icon name={item.icon} size={24}/><div><h3>{item.title}</h3><p>{item.text}</p><span>{item.count}</span></div><Icon name="arrow"/></button>)}</div></>;
}
