import { useState } from 'react';
import { subjects, topics } from '../data/catalog';
import { addDays, formatDate, topicProgress } from '../domain/progress';
import { useStudy } from '../state/StudyProvider';
import { Badge, Heading, Panel, ProgressBar } from '../components/ui';
import { StatsCards } from './Dashboard';

export function ProgressPage() {
  const { state } = useStudy(), [filter, setFilter] = useState('started'), days = Array.from({ length: 14 }, (_, i) => addDays(i - 13));
  const counts = days.map(day => state.attempts.filter(a => a.date === day).length), maximum = Math.max(1, ...counts);
  const filtered = topics.filter(t => filter === 'all' || state.topics[t.id]);
  return <><Heading eyebrow="МОЙ ПУТЬ" title="Прогресс" subtitle="Только твои занятия и ответы. Здесь нет демонстрационных результатов."/><StatsCards progress/><Panel><div className="section-heading"><h2>Последние 14 дней</h2><Badge>Попытки</Badge></div><div className="activity-chart">{days.map((day, i) => <div key={day} title={`${formatDate(day)}: ${counts[i]} попыток`}><span>{counts[i]}</span><i className={counts[i] ? 'has-activity' : ''} style={{ height: `${Math.max(3, counts[i] / maximum * 110)}px` }}/><small>{day.slice(-2)}</small></div>)}</div><p className="small muted">День считается учебным после ответа на задание или отметки занятия. Открытие главной страницы не увеличивает серию.</p></Panel><div className="section-heading"><h2>По предметам</h2></div><div className="subject-progress">{subjects.map(subject => { const all = topics.filter(t => t.subject === subject.id), mastered = all.filter(t => state.topics[t.id]?.status === 'Уверенно').length; return <Panel key={subject.id}><div className="section-heading"><h3>{subject.short}</h3><b>{mastered} / {all.length}</b></div><ProgressBar value={mastered / all.length * 100} label={`Освоение: ${subject.short}`}/><p className="small muted">Тем со статусом «Уверенно»</p></Panel>; })}</div><div className="section-heading"><h2>История тем</h2><select aria-label="Показать прогресс тем" value={filter} onChange={e => setFilter(e.target.value)}><option value="started">С сохранёнными данными</option><option value="all">Все темы</option></select></div><div className="progress-table"><div className="progress-table-head"><span>Тема</span><span>Статус</span><span>Попытки</span><span>Верно / ошибки</span><span>Повторить</span></div>{filtered.map(topic => { const attempts = state.attempts.filter(a => a.topic === topic.id); return <div className="progress-table-row" key={topic.id}><b>{topic.title}</b><span data-label="Статус">{topicProgress(state, topic.id).status}</span><span data-label="Попытки">{attempts.length}</span><span data-label="Верно / ошибки">{attempts.filter(a => a.correct).length} / {attempts.filter(a => !a.correct).length}</span><span data-label="Повторить">{formatDate(state.reviews[`topic:${topic.id}`]?.due)}</span></div>; })}</div>{!filtered.length && <p className="muted">Пока нет сохранённых занятий.</p>}<p className="small muted progress-note">«Задач решено» — разные задания с хотя бы одним верным ответом. Повторные попытки хранятся отдельно; ручная самопроверка также входит в статистику. «Уверенно» — твоя оценка, а не прогноз балла ЕГЭ.</p></>;
}
