import { useState } from 'react';
import { topics, subjects } from '../data/catalog';
import { addDays, formatDate, localDate, reviewIntervals, topicProgress } from '../domain/progress';
import { useStudy } from '../state/StudyProvider';
import { Badge, Button, Empty, Heading, Icon, Panel } from '../components/ui';
import { Schedule } from '../components/Schedule';
import { ErrorCard } from './Errors';

export function ReviewPage({ go }: { go: (page: string) => void }) {
  const { state, mutate } = useStudy(), [period, setPeriod] = useState('due');
  const filtered = topics.filter(t => state.topics[t.id]?.status === 'Повторить' || (state.reviews[`topic:${t.id}`] && (period === 'all' || state.reviews[`topic:${t.id}`].due <= localDate()))).sort((a, b) => (state.reviews[`topic:${a.id}`]?.due ?? '').localeCompare(state.reviews[`topic:${b.id}`]?.due ?? ''));
  const errors = state.errors.filter(e => e.status !== 'закрепил' && (period === 'all' || e.due <= localDate()));
  return <><Heading eyebrow="МАЛЕНЬКИМИ ШАГАМИ" title="Повторение" subtitle="Вернись к теме, пока она не успела забыться."/><div className="filter-row"><select aria-label="Период повторения" value={period} onChange={e => setPeriod(e.target.value)}><option value="due">Сегодня и просроченные</option><option value="all">Весь план повторений</option></select><Badge>{filtered.length + errors.length} карточек</Badge></div><Panel className="review-explainer"><Icon name="calendar"/><p>Интервалы: <b>1 → 3 → 7 → 14 → 30 дней</b>. После успешного повторения следующий интервал растёт. После ошибки возвращается к одному дню. Интервал можно выбрать вручную.</p></Panel>{!filtered.length && !errors.length && <Panel><Empty title="На сегодня всё спокойно">После нового урока или ошибки появится повторение на завтра. Можно открыть любую тему или выбрать лёгкое повторение.</Empty><div className="center"><Button variant="outline" onClick={() => go('easy')}>Лёгкое повторение</Button></div></Panel>}<div className="review-grid">{filtered.map(topic => <Panel key={topic.id}><div className="section-heading"><Badge>{subjects.find(s => s.id === topic.subject)?.short}</Badge><span className="small muted">{formatDate(state.reviews[`topic:${topic.id}`]?.due)}</span></div><h3>{topic.title}</h3><p className="muted">Вспомни правило и объясни один пример без подсказки.</p><div className="button-row"><Button onClick={() => go(`topic/${topic.id}`)}>Открыть тему <Icon name="arrow"/></Button><Button variant="outline" onClick={() => { const id = crypto.randomUUID(); mutate(previous => { const key = `topic:${topic.id}`, stage = Math.min((previous.reviews[key]?.stage ?? 0) + 1, 4), progress = topicProgress(previous, topic.id); return { ...previous, reviews: { ...previous.reviews, [key]: { id: key, targetType: 'topic', targetId: topic.id, due: addDays(reviewIntervals[stage]), stage, last: localDate() } }, topics: { ...previous.topics, [topic.id]: { ...progress, last: localDate(), status: progress.status === 'Повторить' ? 'Изучаю' : progress.status } }, activity: [...previous.activity, { id, topic: topic.id, date: localDate(), kind: 'review' }] }; }); }}>Повторил самостоятельно</Button></div><Schedule topic={topic.id}/></Panel>)}</div>{errors.length > 0 && <><div className="section-heading"><h2>Вернуться к ошибкам</h2></div>{errors.map(error => <ErrorCard key={error.id} error={error}/>)}</>}</>;
}
