import { useId, useState } from 'react';
import { Badge, Button, Panel } from './ui';

type FunctionKind = 'line' | 'square' | 'abs' | 'inverse' | 'sqrt';
const modes: [FunctionKind, string][] = [['line', 'y = x'], ['square', 'y = x²'], ['abs', 'y = |x|'], ['inverse', 'y = 1/x'], ['sqrt', 'y = √x']];
const number = (value: number) => Number.isFinite(value) ? Number(value.toFixed(3)).toLocaleString('ru-RU') : 'Не определено';
const evaluate = (kind: FunctionKind, x: number, a: number, b: number, c: number) => kind === 'line' ? x : kind === 'abs' ? Math.abs(x) : kind === 'inverse' ? 1 / x : kind === 'sqrt' ? Math.sqrt(x) : a * x * x + b * x + c;
export function FunctionPlot({ kind = 'square', a = 1, b = 0, c = 0, point, mini = false }: { kind?: FunctionKind; a?: number; b?: number; c?: number; point?: number; mini?: boolean }) {
  const clip = useId().replaceAll(':', ''), width = 560, height = 340, sx = (x: number) => width / 2 + x * 40, sy = (y: number) => height / 2 - y * 26;
  let path = '', connected = false;
  for (let i = 0; i <= 560; i++) {
    const x = -7 + i / 40, y = evaluate(kind, x, a, b, c);
    if (!Number.isFinite(y) || Math.abs(y) > 10 || (kind === 'inverse' && Math.abs(x) < .06)) { connected = false; continue; }
    path += `${connected ? 'L' : 'M'}${sx(x).toFixed(2)},${sy(y).toFixed(2)} `; connected = true;
  }
  const pointY = point === undefined ? NaN : evaluate(kind, point, a, b, c), vertexX = -b / (2 * a), vertexY = evaluate('square', vertexX, a, b, c), discriminant = b * b - 4 * a * c;
  const roots = kind === 'square' ? a !== 0 ? discriminant >= 0 ? [...new Set([(-b - Math.sqrt(discriminant)) / (2 * a), (-b + Math.sqrt(discriminant)) / (2 * a)])] : [] : b !== 0 ? [-c / b] : [] : [];
  return <svg className={`function-plot ${mini ? 'mini' : ''}`} viewBox={`0 0 ${width} ${height}`} role="img" aria-label={mini ? 'График квадратичной функции' : `График ${modes.find(m => m[0] === kind)?.[1]}, a=${a}, b=${b}, c=${c}`}><defs><clipPath id={clip}><rect width={width} height={height}/></clipPath></defs><g clipPath={`url(#${clip})`}>{Array.from({ length: 15 }, (_, i) => i - 7).map(n => <g key={n}><line className="plot-grid" x1={sx(n)} y1="0" x2={sx(n)} y2={height}/><line className="plot-grid" x1="0" y1={sy(n)} x2={width} y2={sy(n)}/></g>)}<path className="plot-axis" d={`M0 ${sy(0)}H${width} M${sx(0)} 0V${height}`}/><path className="plot-curve" d={path}/>{!mini && <>{[-6, -4, -2, 2, 4, 6].map(n => <g key={n}><text x={sx(n)} y={sy(0) + 20} textAnchor="middle">{n}</text><text x={sx(0) - 10} y={sy(n) + 4} textAnchor="end">{n}</text></g>)}<text x={width - 15} y={sy(0) - 9}>x</text><text x={sx(0) + 9} y="16">y</text>{kind === 'square' && a !== 0 && <circle className="plot-vertex" cx={sx(vertexX)} cy={sy(vertexY)} r="5"/>}{roots.map(x => <circle key={x} className="plot-zero" cx={sx(x)} cy={sy(0)} r="5"/>)}{point !== undefined && Number.isFinite(pointY) && <><path className="plot-guide" d={`M${sx(point)} ${sy(0)}V${sy(pointY)}H${sx(0)}`}/><circle className="plot-point" cx={sx(point)} cy={sy(pointY)} r="6"/></>}</>}</g></svg>;
}
const descriptions: Record<Exclude<FunctionKind, 'square'>, string> = {
  line: 'Область определения: все действительные x. Возрастает на всей области. Нуль: x = 0. При x > 0 положительна, при x < 0 отрицательна. Ни минимума, ни максимума нет.',
  abs: 'Область определения: все действительные x. Убывает до 0, возрастает после 0. Минимум 0 при x = 0. Отрицательных значений нет, максимум не существует.',
  inverse: 'Область определения: x ≠ 0. Убывает на каждом из промежутков (−∞; 0) и (0; +∞) отдельно. Нулей нет. Положительна при x > 0, отрицательна при x < 0. Экстремумов нет.',
  sqrt: 'Область определения: x ≥ 0. Возрастает на [0; +∞). Нуль и минимум при x = 0, y = 0. Положительна при x > 0. Максимума нет.',
};
export function GraphLab() {
  const [kind, setKind] = useState<FunctionKind>('square'), [a, setA] = useState(1), [b, setB] = useState(0), [c, setC] = useState(0), [x, setX] = useState(2);
  const vx = -b / (2 * a), vy = a * vx * vx + b * vx + c, d = b * b - 4 * a * c;
  const zeroes = a !== 0 ? d < 0 ? 'Нет' : [...new Set([(-b - Math.sqrt(d)) / (2 * a), (-b + Math.sqrt(d)) / (2 * a)])].map(number).join('; ') : b !== 0 ? number(-c / b) : c === 0 ? 'Все x' : 'Нет';
  return <Panel className="graph-lab"><div className="section-heading"><div><span className="eyebrow">ЛАБОРАТОРИЯ ГРАФИКОВ</span><h3>Измени правило — посмотри, что изменится</h3></div><Badge tone="teal">Интерактивно</Badge></div><div className="tabs-list function-tabs" role="tablist" aria-label="Вид функции">{modes.map(([id, label]) => <button key={id} type="button" role="tab" aria-selected={kind === id} onClick={() => setKind(id)}>{label}</button>)}</div><div className="graph-layout"><div className="graph-canvas"><FunctionPlot kind={kind} a={a} b={b} c={c} point={x}/><div className="plot-legend"><span><i className="teal-dot"/>График</span>{kind === 'square' && a !== 0 && <><span><i className="amber-dot"/>Вершина</span><span><i className="purple-dot"/>Нули</span></>}<span><i className="blue-dot"/>Выбранная точка</span></div></div><div className="graph-controls"><h4>{kind === 'square' ? 'y = ax² + bx + c' : modes.find(m => m[0] === kind)?.[1]}</h4>{kind === 'square' && <>{([{ label: 'a', value: a, set: setA }, { label: 'b', value: b, set: setB }, { label: 'c', value: c, set: setC }]).map(parameter => <div className="slider-field" key={parameter.label}><label htmlFor={`coefficient-${parameter.label}`}>{parameter.label}<b>{number(parameter.value)}</b></label><input id={`coefficient-${parameter.label}`} type="range" min="-4" max="4" step="0.25" value={parameter.value} aria-label={`Коэффициент ${parameter.label}`} onChange={e => parameter.set(Number(e.target.value))}/></div>)}<Button variant="outline" onClick={() => { setA(1); setB(0); setC(0); }}>Сбросить параметры</Button></>}<div className="slider-field"><label htmlFor="graph-x">Выбери x<b>{number(x)}</b></label><input id="graph-x" type="range" min="-6" max="6" step="0.25" value={x} onChange={e => setX(Number(e.target.value))}/></div></div></div><div className="graph-facts"><div><span>f({number(x)})</span><strong>{number(evaluate(kind, x, a, b, c))}</strong></div>{kind === 'square' && <><div><span>Направление</span><strong>{a === 0 ? 'Не квадратичная' : a > 0 ? 'Ветви вверх' : 'Ветви вниз'}</strong></div><div><span>Вершина</span><strong>{a === 0 ? '—' : `(${number(vx)}; ${number(vy)})`}</strong></div><div><span>Нули функции</span><strong>{zeroes}</strong></div><div><span>Значения функции</span><strong>{a === 0 ? b === 0 ? `y = ${number(c)}` : 'Все y' : `y ${a > 0 ? '≥' : '≤'} ${number(vy)}`}</strong></div></>}</div><p className="small muted">{kind !== 'square' ? descriptions[kind] : a !== 0 ? `Вершина: x₀ = −b/(2a), y₀ = f(x₀). ${a > 0 ? 'До вершины функция убывает, после — возрастает. В вершине минимум, максимума нет.' : 'До вершины функция возрастает, после — убывает. В вершине максимум, минимума нет.'} Область определения — все действительные x. Нули и вершина могут находиться за пределами окна.` : 'При a = 0 функция уже не квадратичная.'}</p></Panel>;
}
