import { useState } from 'react';
import { bridges, questionById, sentences, topicQuestions } from '../data/catalog';
import type { Question, Sentence } from '../domain/types';
import { AnswerBox, Quiz } from './Quiz';
import { GraphLab } from './GraphLab';
import { Badge, Button, Icon, Panel } from './ui';

const number = (value: number) => Number.isFinite(value) ? Number(value.toFixed(3)).toLocaleString('ru-RU') : '—';
function PythonReveal({ kind }: { kind: string }) {
  const [stage, setStage] = useState(0), content = bridges[kind];
  return <Panel className="python-reveal"><Button variant="ghost" onClick={() => setStage(Math.max(1, stage))}>Как это можно решить Python?</Button>{stage >= 1 && <div><h4>1. Алгоритм словами</h4><p>{content.algorithm}</p>{stage === 1 && <Button variant="outline" onClick={() => setStage(2)}>Дальше: псевдокод</Button>}</div>}{stage >= 2 && <div><h4>2. Псевдокод</h4><pre>{content.pseudo}</pre>{stage === 2 && <Button variant="outline" onClick={() => setStage(3)}>Теперь показать Python</Button>}</div>}{stage >= 3 && <div><h4>3. Код</h4><pre>{content.code}</pre><p className="small muted">{content.note} Код можно перенести в VS Code. Выполнение Python в браузере не подключено.</p></div>}</Panel>;
}
function PercentLab() {
  const [amount, setAmount] = useState('800'), [percent, setPercent] = useState(25), [mode, setMode] = useState('part');
  const n = Number(amount), multiplier = percent / 100;
  const result = mode === 'whole' ? n / multiplier : mode === 'increase' ? n * (1 + multiplier) : mode === 'decrease' ? n * (1 - multiplier) : mode === 'chain' ? n * (1 + multiplier) * (1 - multiplier) : n * multiplier;
  const formula = mode === 'whole' ? `${number(n)} ÷ ${percent} × 100` : mode === 'increase' ? `${number(n)} × ${number(1 + multiplier)}` : mode === 'decrease' ? `${number(n)} × ${number(1 - multiplier)}` : mode === 'chain' ? `${number(n)} × ${number(1 + multiplier)} × ${number(1 - multiplier)}` : `${number(n)} ÷ 100 × ${percent}`;
  return <Panel><div className="section-heading"><div><span className="eyebrow">ЛАБОРАТОРИЯ ПРОЦЕНТОВ</span><h3>Где здесь 100%?</h3></div><Badge>Попробуй</Badge></div><select aria-label="Операция с процентами" value={mode} onChange={e => setMode(e.target.value)}><option value="part">Найти процент от числа</option><option value="whole">Восстановить целое</option><option value="increase">Увеличить на процент</option><option value="decrease">Уменьшить на процент</option><option value="chain">Два изменения подряд</option></select><div className="percent-layout"><div><label className="field-label" htmlFor="percent-amount">{mode === 'whole' ? 'Известная часть' : 'Исходное число (100%)'}</label><input id="percent-amount" type="number" value={amount} onChange={e => setAmount(e.target.value)}/><div className="slider-field"><label htmlFor="percent-range">Процент<b>{percent}%</b></label><input id="percent-range" type="range" min="1" max="100" value={percent} onChange={e => setPercent(Number(e.target.value))}/></div><div className="button-row">{[1, 10, 25, 50].map(p => <Button variant="outline" key={p} onClick={() => setPercent(p)}>{p}%</Button>)}</div></div><div className="percent-visual"><div className="hundred-grid" aria-label={`${percent} из 100 равных частей`}>{Array.from({ length: 100 }, (_, i) => <i key={i} className={i < percent ? 'filled' : ''}/>)}</div><p><strong>100% = {number(mode === 'whole' ? result : n)}</strong><span>Исходное целое</span></p></div></div><div className="percent-result"><span>{mode === 'part' ? `${percent}% от ${number(n)}` : mode === 'whole' ? 'Исходное целое' : 'Новое значение'}</span><strong>{amount.trim() ? number(result) : '—'}</strong><p>{amount.trim() ? `${formula} = ${number(result)}` : 'Введи исходное число.'}</p></div></Panel>;
}
const syntaxFields = [['main', 'Главная часть'], ['sub', 'Придаточная часть'], ['ms', 'Подлежащее главной'], ['mp', 'Сказуемое главной'], ['ss', 'Подлежащее придаточной'], ['sp', 'Сказуемое придаточной']] as const;
function SentenceExercise({ sentence, index }: { sentence: Sentence; index: number }) {
  const [field, setField] = useState<(typeof syntaxFields)[number][0]>('main'), [selection, setSelection] = useState<Record<string, number[]>>({}), [role, setRole] = useState('');
  const complete = syntaxFields.every(([key]) => selection[key]?.length) && !!role;
  const serialize = (data: Record<string, number[]>, selectedRole: string) => syntaxFields.map(([key,label]) => label + ': ' + (data[key] ?? []).map(i => sentence.words[i].replace(/[,.!?]/g, '')).join(' ')).join('; ') + '; Связь: ' + selectedRole;
  const expected = Object.fromEntries(syntaxFields.map(([key]) => [key, sentence[key]]));
  const question: Question = { ...questionById.s1, id: `syntax-${index}`, answerType: 'selection', prompt: sentence.text + ' Отметь обе части, их подлежащие и сказуемые. Затем определи роль связующего слова.', answer: serialize(expected, sentence.role), hint: 'В каждой части отдельно найди действие и задай к его участнику вопрос «кто?» или «что?». Не путай вопрос ко всему придаточному с вопросом к одному слову.', solution: sentence.explain };
  return <><blockquote className="sentence-text">{sentence.text}</blockquote><AnswerBox question={question} context="practice" customAnswer={complete ? serialize(selection, role) : ''} customCorrect={serialize(selection, role) === question.answer} customInput={<div><select aria-label="Что выделяем" value={field} onChange={e => setField(e.target.value as typeof field)}>{syntaxFields.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><p className="small muted">Выбери пункт выше, затем отметь нужные слова. Можно выбрать несколько.</p><div className="word-tokens">{sentence.words.map((word, i) => <label key={i} className={`word-token ${(selection[field] ?? []).includes(i) ? 'selected' : ''}`}><input type="checkbox" checked={(selection[field] ?? []).includes(i)} aria-label={`${word}: ${syntaxFields.find(([key]) => key === field)?.[1]}`} onChange={e => setSelection(previous => ({ ...previous, [field]: e.target.checked ? [...(previous[field] ?? []), i].sort((a, b) => a - b) : (previous[field] ?? []).filter(n => n !== i) }))}/>{word}</label>)}</div><div className="selection-summary">{syntaxFields.map(([key, label]) => <div key={key}><span>{label}</span><b>{selection[key]?.map(i => sentence.words[i]).join(' ') || 'Не выбрано'}</b></div>)}</div><label className="field-label">Роль связующего слова<select aria-label="Роль связующего слова" value={role} onChange={e => setRole(e.target.value)}><option value="">Роль связующего слова</option>{['Союз — не член предложения', 'Союзное слово — подлежащее', 'Союзное слово — дополнение'].map(label => <option key={label}>{label}</option>)}</select></label></div>}/></>;
}
function SentenceTrainer() {
  const [index, setIndex] = useState(0);
  return <Panel className="sentence-trainer"><div className="section-heading"><div><span className="eyebrow">РАЗБОР ПРЕДЛОЖЕНИЯ</span><h3>Найди, кто что делает</h3></div><Badge tone="purple">{index + 1} / {sentences.length}</Badge></div><SentenceExercise key={index} sentence={sentences[index]} index={index}/><Button variant="outline" onClick={() => setIndex((index + 1) % sentences.length)}>Другое предложение <Icon name="arrow"/></Button></Panel>;
}
const binaryValues = [45, 26, 37, 19, 52, 63]; // Exactly the existing reference sequence.
function BinaryExercise({ value, reverse }: { value: number; reverse: boolean }) {
  const [selected, setSelected] = useState<number[]>([]), weights = [32, 16, 8, 4, 2, 1], bits = value.toString(2).padStart(6, '0'), expected = weights.filter((_, i) => bits[i] === '1');
  const question: Question = { ...questionById.b1, id: `bits-${reverse ? 'r' : 'f'}-${value}`, answerType: 'selection', prompt: reverse ? `Собери двоичную запись числа ${value}₁₀. Выбери веса, из которых оно складывается.` : `Перед тобой ${bits}₂. Выбери веса всех разрядов с единицей.`, answer: expected.join(';'), hint: reverse ? 'Сравни число с самым большим подходящим весом. Вычти этот вес и продолжай с остатком.' : 'Каждый разряд равен 0 или 1. Вес добавляется к сумме только там, где в исходной записи стоит 1.', solution: `${expected.join(' + ')} = ${value}. Двоичная запись: ${value.toString(2)}₂.${reverse ? ' При делении на 2 читай остатки снизу вверх.' : ''}` };
  return <AnswerBox question={question} context="practice" customAnswer={selected.join(';')} customCorrect={selected.join(';') === question.answer} customInput={<div className="bit-grid">{weights.map((weight, i) => <label key={weight} className={`bit-cell ${selected.includes(weight) ? 'selected' : ''}`}><span className="bit-digit">{reverse ? selected.includes(weight) ? '1' : '0' : bits[i]}</span><span>2<sup>{5 - i}</sup></span><b>{weight}</b><input aria-label={`Вес ${weight}`} type="checkbox" checked={selected.includes(weight)} onChange={e => setSelected(previous => e.target.checked ? weights.filter(w => w === weight || previous.includes(w)) : previous.filter(w => w !== weight))}/></label>)}</div>}/>;
}
function BinaryTrainer() {
  const [index, setIndex] = useState(0), [direction, setDirection] = useState('forward');
  return <><Panel><div className="section-heading"><div><span className="eyebrow">ТРЕНАЖЁР РАЗРЯДОВ</span><h3>Каждая единица вносит свой вес</h3></div></div><select aria-label="Направление перевода" value={direction} onChange={e => setDirection(e.target.value)}><option value="forward">Из двоичной в десятичную</option><option value="reverse">Из десятичной в двоичную</option></select><BinaryExercise key={`${index}-${direction}`} value={binaryValues[index]} reverse={direction === 'reverse'}/><Button variant="outline" onClick={() => setIndex((index + 1) % binaryValues.length)}>Другое число <Icon name="arrow"/></Button></Panel><PythonReveal key={direction} kind={direction === 'forward' ? 'binary-forward' : 'binary'}/></>;
}
function EncodingExercise({ count }: { count: number }) {
  const [bits, setBits] = useState(''), expected = Math.ceil(Math.log2(count));
  const question: Question = { ...questionById.c1, id: `codes-${count}`, prompt: `Размер алфавита — ${count}. Выбери минимальное число бит на символ.`, answer: String(expected), hint: 'Нужно, чтобы число комбинаций 2ⁱ было не меньше размера алфавита. Проверь и выбранное i, и предыдущее.', solution: `2^${expected - 1} = ${2 ** (expected - 1)} — недостаточно; 2^${expected} = ${2 ** expected} — достаточно. Минимально нужно ${expected} бит.` };
  return <AnswerBox question={question} context="practice" customAnswer={bits} customInput={<select aria-label="Количество бит" value={bits} onChange={e => setBits(e.target.value)}><option value="">Количество бит</option>{Array.from({ length: 16 }, (_, i) => <option value={i + 1} key={i}>Битов: {i + 1}</option>)}</select>}/>;
}
function EncodingTrainer() {
  const [input, setInput] = useState('33'), [count, setCount] = useState(33), valid = Number.isInteger(Number(input)) && Number(input) >= 2 && Number(input) <= 65536;
  return <><Panel><div className="section-heading"><div><span className="eyebrow">РАВНОМЕРНОЕ КОДИРОВАНИЕ</span><h3>Хватит ли разных кодов?</h3></div></div><div className="inline-form"><label htmlFor="alphabet-size">Символов в алфавите</label><input id="alphabet-size" type="number" min="2" max="65536" value={input} onChange={e => setInput(e.target.value)}/><Button variant="outline" disabled={!valid} onClick={() => setCount(Number(input))}>Новое задание</Button></div><p className="small muted">От 2 до 65 536 символов. У каждого символа свой код одинаковой длины.</p><EncodingExercise key={count} count={count}/></Panel><PythonReveal kind="encoding"/></>;
}
export function Practice({ topic }: { topic: string }) {
  if (topic === 'functions') return <GraphLab/>;
  if (topic === 'percent') return <PercentLab/>;
  if (topic === 'sentence') return <SentenceTrainer/>;
  if (topic === 'binary') return <BinaryTrainer/>;
  if (topic === 'encoding') return <EncodingTrainer/>;
  return <Quiz items={topicQuestions(topic)} context="practice" title={topic === 'unionwords' ? 'Союз или союзное слово?' : 'Сначала предскажи результат'}/>;
}
