import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
import {checkContentBank} from '../../scripts/content-bank.mjs';import {emptyState,recordAttempt} from '../../src/domain/progress.ts';import {beginReview} from '../../src/domain/adaptive.ts';import {startTopicTest} from '../../src/domain/study-flow.ts';import {parseBackup} from '../../src/domain/backup.ts';
const {chromium}=createRequire(pathToFileURL(path.join(process.argv[2],'_runtime.js')))('playwright');
const directory=path.resolve(process.argv[3]),oldDirectory=path.resolve(process.argv[4]),stamp=new Date().toISOString().replace(/[:.]/g,'-'),profile=path.resolve('work/study-flow-profile-'+stamp),{questions:bank}=checkContentBank();
const walk=(d,root=d)=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name),root):[[path.relative(root,path.join(d,e.name)).replaceAll('\\','/'),fs.readFileSync(path.join(d,e.name))]]);
let resources=new Map(walk(oldDirectory)),next=new Map(walk(directory));const prefix='/ege-2027-offline/';
const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://local.test').pathname;if(p==='/seed.html'){res.writeHead(200,{'Content-Type':'text/html'});res.end('<title>Own fixture</title>');return;}const file=p.startsWith(prefix)?p.slice(prefix.length)||'index.html':null,bytes=resources.get(file);if(!bytes){res.writeHead(404);res.end();return;}const mime=file.endsWith('.js')?'text/javascript':file.endsWith('.wasm')?'application/wasm':file.endsWith('.html')?'text/html':file.endsWith('.css')?'text/css':file.endsWith('.json')?'application/json':file.endsWith('.webmanifest')?'application/manifest+json':file.endsWith('.svg')?'image/svg+xml':file.endsWith('.png')?'image/png':'application/octet-stream';res.writeHead(200,{'Content-Type':mime,'Cache-Control':'no-store'});res.end(bytes);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const host='http://127.0.0.1:'+server.address().port,base=host+prefix;
const checks=[],errors=[],external=new Set();let context,page;
const launch=()=>chromium.launchPersistentContext(profile,{channel:'msedge',headless:true,serviceWorkers:'allow',acceptDownloads:true,viewport:{width:390,height:844},isMobile:true,hasTouch:true});
const watch=()=>{page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(host+'/'))external.add(r.url());});};
const state=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('ege-local-center',1);r.onsuccess=()=>{const db=r.result,q=db.transaction('progress','readonly').objectStore('progress').get('current');q.onsuccess=()=>{resolve(q.result);db.close();};q.onerror=()=>reject(q.error);};}));
async function saved(predicate){for(let i=0;i<400;i++){const s=await state();if(predicate(s))return s;await new Promise(r=>setTimeout(r,30));}throw Error('Expected saved state; training='+JSON.stringify((await state()).training)+' attempts='+JSON.stringify((await state()).attempts.map(a=>a.questionId)));}
const ready=()=>page.getByText('Полный учебный комплект сохранён:',{exact:false}).waitFor({timeout:90000});
const python=()=>page.getByText('Python готов · Запуск — эксперимент, проверка — учебный результат.',{exact:true}).waitFor({timeout:90000});
const pass=name=>{checks.push(name);console.log('PASS '+name);};
async function go(route){await page.goto(base+'#'+route);await page.getByRole('heading',{level:1}).waitFor();}
async function code(value){await python();await page.getByLabel('Код решения',{exact:true}).fill(value);await saved(s=>Object.values(s.codeDrafts??{}).some(d=>d.code===value));}
async function runCode(){await page.getByRole('button',{name:'Запустить',exact:true}).click();await python();}
async function checkCode(){await page.getByRole('button',{name:'Проверить решение',exact:true}).click();await python();}
async function viewerClose(back=false){if(back)await page.evaluate(()=>history.back());else await page.getByRole('button',{name:'Закрыть вывод',exact:true}).click();await page.getByRole('dialog',{name:'Полный вывод Python',exact:true}).waitFor({state:'hidden'});}
try{
 const old=bank.find(q=>q.id==='p2'),draftQ=bank.find(q=>q.id==='b1-python-03');let fixture=recordAttempt(emptyState('published-034-bank'),old,'12',false,'test','old-error',new Date('2026-10-08T12:00:00Z'));fixture.topics.percent.note='Own update fixture';fixture.codeDrafts={[draftQ.id]:{schemaVersion:1,questionVersion:draftQ.version,code:'# Own preserved draft',stdin:'2\n3',updatedAt:'2026-10-08T12:00:00.000Z'}};fixture=startTopicTest(fixture,'percent',[old],'old-frozen');fixture=beginReview(fixture,[{question:old,score:1,reasons:[],firstCorrect:null,correct:null,attemptIds:[]}],5,'math','old-adaptive');
 context=await launch();page=context.pages()[0];watch();await page.goto(host+'/seed.html');await page.evaluate(s=>new Promise(resolve=>{const r=indexedDB.open('ege-local-center',1);r.onupgradeneeded=()=>r.result.createObjectStore('progress');r.onsuccess=()=>{const d=r.result,t=d.transaction('progress','readwrite');t.objectStore('progress').put(s,'current');t.oncomplete=()=>{d.close();resolve();};};}),fixture);await go('settings');await ready();assert.deepEqual(await state(),fixture);resources=next;await page.evaluate(async()=>{await(await navigator.serviceWorker.getRegistration()).update();});await page.getByText('Новая версия готова.',{exact:false}).waitFor({timeout:90000});assert.deepEqual(await state(),fixture);await context.close();context=await launch();await context.setOffline(true);page=context.pages()[0];watch();await go('settings');await ready();assert.deepEqual(await state(),fixture);pass('Local update from published-commit 0.3.4 preserves attempts, errors, note, active mini-test, adaptive snapshot and Python draft exactly after cold offline activation');
 const lessons=JSON.parse(fs.readFileSync('src/data/stage3b2-lessons.json')).lessons,reference=JSON.parse(fs.readFileSync('src/data/reference.json')),readyTopics=new Set([...reference.topics.filter(t=>t.live).map(t=>t.id),...JSON.parse(fs.readFileSync('src/data/stage3b1-lessons.json')).lessons.map(l=>l.topic),...lessons.map(l=>l.topic)]);assert.equal(readyTopics.size,44);
 for(const width of [320,360,390,1100]){await page.setViewportSize({width,height:844});for(const topic of ['quadratic','inequalities','word','probability','logarithms','trigonometry','complex','participles','graphs','tables','algorithms','py-files']){await go('topic/'+topic);assert.ok(await page.getByRole('tab',{name:'Практика',exact:true}).count());for(const dark of [false,true]){await page.evaluate(d=>document.documentElement.classList.toggle('dark',d),dark);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),width+' '+topic);}}}pass('Expanded lessons, long conditions and examples fit 320/360/390/desktop in both themes');
 await page.setViewportSize({width:390,height:844});for(const topic of reference.topics){await go('topic/'+topic.id);if(readyTopics.has(topic.id))await page.getByRole('tab',{name:'Мини-тест',exact:true}).waitFor();else await page.getByText('План · урок ещё не добавлен',{exact:true}).waitFor();}assert.deepEqual(await state(),fixture);pass('All 67 routes and 44 filled modules open offline without changing progress; remaining 23 stay honest plan pages');
 await go('topic/quadratic');await page.getByRole('tab',{name:'Практика',exact:true}).click();await page.getByLabel('Твой ответ',{exact:true}).fill('5');await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();await page.getByRole('button',{name:'Попробовать ещё раз',exact:true}).click();await page.getByLabel('Твой ответ',{exact:true}).fill('2');await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();await saved(s=>s.training?.length===2);assert.deepEqual((await state()).attempts,fixture.attempts);assert.deepEqual((await state()).errors,fixture.errors);pass('New-topic practice permits correction and stores training separately from scored history');
 await go('topic/inequalities');await page.getByRole('tab',{name:'Мини-тест',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Показать подсказку',exact:true}).count(),0);await page.getByLabel('Твой ответ',{exact:true}).fill('text');await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();await page.getByRole('alert').waitFor();assert.equal((await state()).attempts.length,1);await page.getByLabel('Твой ответ',{exact:true}).fill('1');await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();await saved(s=>s.attempts.length===2);await page.getByRole('button',{name:'Попробовать ещё раз',exact:true}).click();await page.getByLabel('Твой ответ',{exact:true}).fill('0');await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();assert.equal((await state()).attempts.length,2);await page.getByRole('button',{name:'Следующий вопрос',exact:true}).click();await page.getByLabel('Твой ответ',{exact:true}).fill('6');await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();await page.getByRole('button',{name:'Завершить мини-тест',exact:true}).click();assert.ok((await page.locator('.quiz-finish').textContent()).includes('1 из 2'));pass('Two independent new controls freeze first results; invalid format is unscored and correction does not rewrite the first error');
 const codeQ=bank.find(q=>q.id==='b2-informatics-algo-steps'),beforeCode=await state(),withCode=startTopicTest(beforeCode,'algorithms',[codeQ],'new-program-control');await context.setOffline(false);await page.goto(host+'/seed.html');await page.evaluate(s=>new Promise(resolve=>{const r=indexedDB.open('ege-local-center',1);r.onsuccess=()=>{const d=r.result,t=d.transaction('progress','readwrite');t.objectStore('progress').put(s,'current');t.oncomplete=()=>{d.close();resolve();};};}),withCode);await context.setOffline(true);await go('topic/algorithms');await page.getByRole('tab',{name:'Мини-тест',exact:true}).click();await code('def routes(n):\n    return 1');await runCode();assert.deepEqual((await state()).attempts,beforeCode.attempts);await checkCode();await saved(s=>s.attempts.length===beforeCode.attempts.length+1);assert.equal((await state()).topicTests.at(-1).items[0].firstCorrect,false);await code(codeQ.solution);await checkCode();await saved(s=>s.topicTests.at(-1).items[0].correct===true);assert.equal((await state()).attempts.length,beforeCode.attempts.length+1);const final=await state();assert.equal(final.codeDrafts[codeQ.id].code,codeQ.solution);pass('New DP function executes real Python offline, rejects incomplete algorithm, passes corrected solution and keeps first control result/draft');
 await go('settings');const event=page.waitForEvent('download');await page.getByRole('button',{name:'Экспортировать JSON',exact:true}).click();const text=fs.readFileSync(await(await event).path(),'utf8');assert.deepEqual(parseBackup(text).data,final);await go('topic/percent');await page.getByLabel('Моя заметка по теме',{exact:true}).fill('Own changed fixture');await saved(s=>s.topics.percent.note==='Own changed fixture');await go('settings');await page.locator('input[type=file]').setInputFiles({name:'own-new-bank-backup.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.getByLabel('Понимаю, что импорт заменит текущий прогресс').check();await page.getByRole('button',{name:'Заменить данные',exact:true}).click();await page.getByText('Данные восстановлены из резервной копии.',{exact:false}).waitFor();assert.deepEqual(await state(),final);await context.close();context=await launch();await context.setOffline(true);page=context.pages()[0];watch();await go('settings');await ready();assert.deepEqual(await state(),final);await go('topic/algorithms');await page.getByRole('tab',{name:'Мини-тест',exact:true}).click();await python();assert.equal(await page.getByLabel('Код решения',{exact:true}).inputValue(),codeQ.solution);assert.equal((await state()).topicTests.find(s=>s.id==='old-frozen').items[0].question.prompt,old.prompt);pass('New/old snapshots and both exercise drafts survive UI JSON export/import and another cold offline browser restart');assert.deepEqual(errors,[]);assert.equal(external.size,0);fs.writeFileSync('outputs/CONTENT3B2-BROWSER.json',JSON.stringify({checks,errors,externalRequests:[...external],profile},null,2));
}finally{if(context)await context.close();await new Promise(r=>server.close(r));}