// Isolated browser profiles, authored fixtures, local production server. No user data.
import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import ts from 'typescript';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';import {execFileSync} from 'node:child_process';
import {checkContentBank} from '../../scripts/content-bank.mjs';import {emptyState} from '../../src/domain/progress.ts';import {beginReview} from '../../src/domain/adaptive.ts';import {parseBackup} from '../../src/domain/backup.ts';
const {chromium}=createRequire(pathToFileURL(path.join(process.argv[2],'_runtime.js')))('playwright');
const directory=path.resolve(process.argv[3]),oldDirectory=path.resolve(process.argv[4]),stamp=new Date().toISOString().replace(/[:.]/g,'-'),profile=path.resolve('work/polish-profile-'+stamp),fixtures=path.resolve('work/learning-fixtures-'+stamp);
fs.mkdirSync(fixtures,{recursive:true});const {questions:bank}=checkContentBank(),wave=bank.filter(q=>q.id.startsWith('b1-')),codes=wave.filter(q=>q.answerType==='code');
const walk=(d,root=d)=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name),root):[[path.relative(root,path.join(d,e.name)).replaceAll('\\','/'),fs.readFileSync(path.join(d,e.name))]]);
const resources=new Map(walk(directory)),old=new Map(walk(oldDirectory)),prefix='/ege-2027-offline/';let current=old;
const modules=new Map();for(const name of ['runner','tasks','assessment','grading']){let src=fs.readFileSync('src/python/'+name+'.ts','utf8');if(name==='runner')src=src.replace("import source from './worker.js?raw';",'const source='+JSON.stringify(fs.readFileSync('src/python/worker.js','utf8'))+';').replace("import sandbox from './sandbox.html?raw';",'const sandbox='+JSON.stringify(fs.readFileSync('src/python/sandbox.html','utf8'))+';').replaceAll('import.meta.env.BASE_URL',JSON.stringify(prefix));modules.set('/harness/'+name+'.mjs',ts.transpileModule(src,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText.replaceAll(/from ['"]\.\/(runner|tasks|assessment)(?:\.ts)?['"]/g,(_m,n)=>"from '/harness/"+n+".mjs'"));}
const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://local.test').pathname;if(p==='/seed.html'){res.writeHead(200,{'Content-Type':'text/html'});res.end('<!doctype html><title>Own test fixture</title>');return;}const file=p.startsWith(prefix)?p.slice(prefix.length)||'index.html':null,bytes=modules.get(p)??current.get(file);if(!bytes){res.writeHead(404);res.end();return;}const extension=file??p;const mime=extension.endsWith('.mjs')||extension.endsWith('.js')?'text/javascript':extension.endsWith('.wasm')?'application/wasm':extension.endsWith('.html')?'text/html':extension.endsWith('.css')?'text/css':extension.endsWith('.webmanifest')?'application/manifest+json':extension.endsWith('.svg')?'image/svg+xml':extension.endsWith('.png')?'image/png':'application/octet-stream';res.writeHead(200,{'Content-Type':mime,'Cache-Control':'no-store'});res.end(bytes);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const host='http://127.0.0.1:'+server.address().port,base=host+prefix;
const launch=()=>chromium.launchPersistentContext(profile,{channel:'msedge',headless:true,serviceWorkers:'allow',acceptDownloads:true,viewport:{width:390,height:844},isMobile:true,hasTouch:true});
let context,page;const checks=[],errors=[],external=new Set(),checksPerProgram=[];
const watch=()=>{page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(host+'/'))external.add(r.url());});};
const ready=()=>page.getByText('Полный учебный комплект сохранён:',{exact:false}).waitFor({timeout:60000});
const python=()=>page.getByText('Python готов · Запуск — эксперимент, проверка — учебный результат.',{exact:true}).waitFor({timeout:90000});
const state=()=>page.evaluate(()=>new Promise((resolve,reject)=>{const r=indexedDB.open('ege-local-center',1);r.onsuccess=()=>{const db=r.result,q=db.transaction('progress','readonly').objectStore('progress').get('current');q.onsuccess=()=>{resolve(q.result);db.close();};q.onerror=()=>reject(q.error);};}));
async function saved(predicate){for(let i=0;i<200;i++){const s=await state();if(predicate(s))return s;await new Promise(r=>setTimeout(r,30));}throw Error('Expected persisted state not found');}
async function seed(s){await context.setOffline(false);await page.goto(host+'/seed.html');await page.evaluate(s=>new Promise((resolve,reject)=>{const r=indexedDB.open('ege-local-center',1);r.onupgradeneeded=()=>r.result.createObjectStore('progress');r.onsuccess=()=>{const db=r.result,tx=db.transaction('progress','readwrite');tx.objectStore('progress').put(s,'current');tx.oncomplete=()=>{db.close();resolve();};tx.onerror=()=>reject(tx.error);};}),s);await page.goto(base+'#review-today');}
const pass=s=>{checks.push(s);console.log('PASS '+s);};
async function edit(code){await python();await page.getByLabel('Код решения',{exact:true}).fill(code);await saved(s=>Object.values(s.codeDrafts??{}).some(d=>d.code===code));}
async function check(){await page.getByRole('button',{name:'Проверить решение',exact:true}).click();await python();}
async function importText(text){await page.locator('input[type=file]').setInputFiles({name:'own-backup.json',mimeType:'application/json',buffer:Buffer.from(text)});await page.getByRole('dialog').waitFor();await page.getByLabel('Понимаю, что импорт заменит текущий прогресс').check();await page.getByRole('button',{name:'Заменить данные',exact:true}).click();await page.getByText('Данные восстановлены из резервной копии.',{exact:false}).waitFor();}
const item=q=>({question:q,score:1,reasons:[],firstCorrect:null,correct:null,attemptIds:[]});

try{
 current=resources;context=await launch();page=context.pages()[0];watch();await page.goto(base+'#settings');await ready();

 const literal='& <img src="missing" onerror="window.__mathExecuted=true"> <script>window.__mathExecuted=true</script> https://example.test/?ratio=3/4 C:/lessons/ratio=2/3.txt '+String.fromCharCode(96)+'print(4/5)'+String.fromCharCode(96)+'; дробь 1/2.';
 const htmlQuestion={...bank.find(q=>q.id==='b1-math-05'),origin:'custom',source:'Own browser safety fixture',prompt:literal};
 await seed(beginReview(emptyState('safety-control'),[item(htmlQuestion)],5,'math','safety'));await page.locator('.question-prompt').waitFor();assert.equal(await page.locator('.question-prompt').textContent(),literal);assert.equal(await page.locator('.question-prompt img,.question-prompt script').count(),0);assert.equal(await page.locator('.question-prompt .math-fraction').count(),1);assert.equal(await page.evaluate(()=>window.__mathExecuted),undefined);
 await page.getByLabel('Твой ответ',{exact:true}).fill(literal);assert.equal(await page.getByLabel('Твой ответ',{exact:true}).inputValue(),literal);await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();assert.equal((await state()).attempts.length,0);const safetyBackup=JSON.stringify({format:'ege-progress-backup',backupVersion:2,appVersion:'0.3.3',createdAt:new Date().toISOString(),data:await state()});assert.equal(parseBackup(safetyBackup).data.adaptive.sessions[0].items[0].question.prompt,literal);
 pass('Actual question renders HTML as literal text, never executes script/events, preserves URLs/paths/inline code and raw input; snapshot survives backup');
 for(const width of [1440,390,360,320]){
  await page.setViewportSize({width,height:900});await page.goto(base+'#topic/fractions');await page.getByRole('heading',{name:'Дроби',level:1}).waitFor();
  const example=page.locator('pre.math-example').first();assert.equal(await page.locator('pre.math-example').count(),2);assert.ok(await example.locator('.math-fraction').count()>=11);
  const layout=await example.locator('.math-fraction').first().evaluate(el=>{const a=el.querySelector('.math-numerator'),b=el.querySelector('.math-denominator'),ar=a.getBoundingClientRect(),br=b.getBoundingClientRect();return{top:ar.top,bottom:ar.bottom,denominatorTop:br.top,font:parseFloat(getComputedStyle(a).fontSize),border:parseFloat(getComputedStyle(a).borderBottomWidth),width:document.documentElement.scrollWidth,viewport:innerWidth};});
  assert.ok(layout.bottom<=layout.denominatorTop+.1);assert.ok(layout.border>=1);assert.ok(layout.font>=15);assert.ok(layout.width<=layout.viewport,'overflow '+JSON.stringify(layout));
  await example.screenshot({path:'outputs/polish-fractions-'+width+'.png'});if(width===390)await page.screenshot({path:'outputs/polish-mobile-fractions.png',fullPage:true});
 }
 pass('Fractions in the real worked example have stacked numerator/bar/denominator, font >=15px and no page overflow at 320/360/390/1440px');
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>{document.documentElement.classList.add('dark');});await page.locator('pre.math-example').first().screenshot({path:'outputs/polish-fractions-dark.png'});await page.evaluate(()=>document.documentElement.classList.remove('dark'));
 const fraction=bank.find(q=>q.id==='b1-math-05');await seed(beginReview(emptyState('fraction-control'),[item(fraction)],5,'math','fractions'));await page.locator('.question-prompt').waitFor();assert.equal(await page.locator('.question-prompt .math-fraction').count(),2);
 await page.getByRole('button',{name:'Показать подсказку',exact:true}).click();await page.getByLabel('Твой ответ',{exact:true}).fill('word');await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();assert.equal((await state()).attempts.length,0);
 await page.getByLabel('Твой ответ',{exact:true}).fill('1/2');await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();await saved(s=>s.errors.length===1);await page.getByRole('button',{name:'Показать полное решение',exact:false}).click();assert.ok(await page.locator('.solution .math-fraction').count()>0);
 await page.goto(base+'#errors');assert.equal(await page.locator('.error-card h3 .math-fraction').count(),2);await page.getByRole('button',{name:'Разобрать ошибку',exact:true}).click();assert.ok(await page.locator('.error-details .math-fraction').count()>0);assert.equal(await page.locator('.wrong-answer').textContent(),'Мой ответ: 1/2');
 pass('Question, explicit solution and saved error render fractions; invalid text is not scored and the answer input keeps slash notation');
 await seed(beginReview(emptyState('fraction-correct'),[item(fraction)],5,'math','fraction-correct'));await page.getByLabel('Твой ответ',{exact:true}).fill('11/12');await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();await saved(s=>s.attempts.some(a=>a.answer==='11/12'&&a.correct));
 pass('A typed fraction is checked unchanged and recorded correctly');
 for(const topic of ['powers','roots','functions','percent','encoding']){await page.goto(base+'#topic/'+topic);await page.getByRole('tab',{name:'Объяснение',exact:true}).waitFor();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),topic);}
 await page.goto(base+'#topic/functions');const code=page.locator('pre').filter({hasText:'def f(x)'});assert.equal(await code.count(),1);assert.equal(await code.locator('[data-math-kind]').count(),0);assert.equal(await page.locator('code [data-math-kind]').count(),0);
 pass('Powers, roots, functions and information formulas fit mobile; embedded Python and inline code are unchanged');
 const oldCodes=['python','informatics'].flatMap(subject=>JSON.parse(execFileSync('git',['show','2470167:src/data/banks/stage3b1-'+subject+'.json'],{encoding:'utf8'})).questions).filter(q=>q.answerType==='code');
 const old=oldCodes.find(q=>q.id==='b1-python-16'),revised=bank.find(q=>q.id===old.id),baseline=emptyState('draft-control');baseline.codeDrafts={[old.id]:{schemaVersion:1,questionVersion:1,code:'total = 0\nfor word in input().split():\n    total += int(word)\nprint(total)',stdin:'1 2 3',updatedAt:new Date().toISOString()}};
 await seed(baseline);await page.goto(base+'#topic/'+old.topic);await page.getByRole('tab',{name:'Практика',exact:true}).click();await python();assert.equal(await page.getByLabel('Код решения',{exact:true}).inputValue(),baseline.codeDrafts[old.id].code);assert.equal(await page.getByText('Условие обновилось.',{exact:false}).count(),1);
 await page.locator('details').filter({has:page.getByText('Разбор и решение — по запросу',{exact:true})}).locator('summary').click();await page.getByRole('button',{name:'Показать полное решение',exact:true}).click();assert.equal(await page.locator('.code-explanation pre').count(),1);assert.ok((await page.locator('.code-explanation pre').textContent()).includes('for word'));assert.ok(!(await page.locator('.code-explanation').textContent()).includes(''+String.fromCharCode(96).repeat(3)));await page.screenshot({path:'outputs/polish-mobile-python-explanation.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await context.setOffline(true);await context.close();context=await launch();await context.setOffline(true);page=context.pages()[0];watch();await page.goto(base+'#topic/'+old.topic);await page.getByRole('tab',{name:'Практика',exact:true}).click();await python();assert.equal(await page.getByLabel('Код решения',{exact:true}).inputValue(),baseline.codeDrafts[old.id].code);assert.equal((await state()).codeDrafts[old.id].questionVersion,1);
 await page.goto(base+'#settings');await ready();const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'Экспортировать JSON',exact:true}).click();const backup=fs.readFileSync(await(await downloadEvent).path(),'utf8');assert.equal(parseBackup(backup).data.codeDrafts[old.id].code,baseline.codeDrafts[old.id].code);
 await importText(backup);assert.equal((await state()).codeDrafts[old.id].questionVersion,1);
 pass('Version 1 draft opens against revision 3, survives full cold offline closure, and exports/imports unchanged; beginner loop displays as code');
 await context.setOffline(false);await page.evaluate(async()=>{window._grader=(await import('/harness/grading.mjs')).gradePython;});await context.setOffline(true);
 const overfit={
 'b1-informatics-22':'n=int(input())\nprint(sum(range(1,min(n,10)+1)))',
 'b1-python-09':'n=int(input())\nfor i in range(min(n,4)): print(i)',
 'b1-python-16':'nums=[int(x) for x in input().split()]\nprint(sum(nums[:3]))',
 'b1-python-23':'def double(x):\n    return max(-11,min(x,11))*2',
 'b1-informatics-25':'print(int(input()[-6:],2))',
 };
 const overfitResults=[];
 for(const [id,code] of Object.entries(overfit)){const before=oldCodes.find(q=>q.id===id),after=bank.find(q=>q.id===id);const result=await page.evaluate(async({code,before,after})=>({before:await window._grader(code,before),after:await window._grader(code,after)}),{code,before:before.python,after:after.python});assert.ok(result.before.every(r=>r.passed),id+' did not pass old cases');assert.ok(result.after.some(r=>!r.passed),id+' still passes strengthened cases');overfitResults.push({id,oldPassed:result.before.length,newFailed:result.after.filter(r=>!r.passed).length});console.log('OVERFIT '+id+' old passed '+result.before.length+', new failed '+overfitResults.at(-1).newFailed);}
 pass('Five small-example-only programs pass the original cases but fail the new in-domain boundary cases with real CPython');
 assert.deepEqual(errors,[]);assert.equal(external.size,0);fs.writeFileSync('outputs/POLISH032-BROWSER.json',JSON.stringify({checks,overfitResults,errors,externalRequests:[...external]},null,2));
}finally{if(context)await context.close();await new Promise(r=>server.close(r));}
