import fs from 'node:fs';import path from 'node:path';import http from 'node:http';import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {pathToFileURL} from 'node:url';
import {checkContentBank} from '../../scripts/content-bank.mjs';import {emptyState,recordAttempt} from '../../src/domain/progress.ts';import {parseBackup} from '../../src/domain/backup.ts';
const {chromium}=createRequire(pathToFileURL(path.join(process.argv[2],'_runtime.js')))('playwright'),directory=path.resolve(process.argv[3]),profile=path.resolve('work/release034-label-profile-'+new Date().toISOString().replace(/[:.]/g,'-')),bank=checkContentBank().questions;
const walk=(d,root=d)=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.isDirectory()?walk(path.join(d,e.name),root):[[path.relative(root,path.join(d,e.name)).replaceAll('\\','/'),fs.readFileSync(path.join(d,e.name))]]),files=new Map(walk(directory)),prefix='/ege-2027-offline/';
const appVersion=JSON.parse(fs.readFileSync('package.json')).version;
const server=http.createServer((req,res)=>{const p=new URL(req.url,'http://local.test').pathname;if(p==='/seed.html'){res.writeHead(200,{'Content-Type':'text/html'});res.end('<title>Own fixture</title>');return;}const f=p.startsWith(prefix)?p.slice(prefix.length)||'index.html':null,b=files.get(f);if(!b){res.writeHead(404);res.end();return;}const type=f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':f.endsWith('.html')?'text/html':f.endsWith('.webmanifest')?'application/manifest+json':f.endsWith('.svg')?'image/svg+xml':f.endsWith('.png')?'image/png':'application/octet-stream';res.writeHead(200,{'Content-Type':type});res.end(b);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const host='http://127.0.0.1:'+server.address().port,base=host+prefix,checks=[],errors=[],external=new Set();let context;
try{
 context=await chromium.launchPersistentContext(profile,{channel:'msedge',headless:true,viewport:{width:390,height:844},isMobile:true,hasTouch:true,serviceWorkers:'allow',acceptDownloads:true});const page=context.pages()[0];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(host+'/'))external.add(r.url());});
 const q=bank.find(q=>q.id==='py-tuples-q'),legacy=recordAttempt(emptyState('legacy-control'),q,'0',false,'practice','legacy-practice',new Date('2026-10-08T12:00:00Z'));await page.goto(host+'/seed.html');await page.evaluate(s=>new Promise(resolve=>{const r=indexedDB.open('ege-local-center',1);r.onupgradeneeded=()=>r.result.createObjectStore('progress');r.onsuccess=()=>{const d=r.result,t=d.transaction('progress','readwrite');t.objectStore('progress').put(s,'current');t.oncomplete=()=>{d.close();resolve();};};}),legacy);
 const state=()=>page.evaluate(()=>new Promise(resolve=>{const r=indexedDB.open('ege-local-center',1);r.onsuccess=()=>{const d=r.result,v=d.transaction('progress','readonly').objectStore('progress').get('current');v.onsuccess=()=>{resolve(v.result);d.close();};};}));
 const pass=s=>{checks.push(s);console.log('PASS '+s);};const count=label=>page.locator('.topic-stat').filter({has:page.getByText(label,{exact:true})}).locator('b').textContent();
 await page.goto(base+'#settings');await page.getByText('Версия '+appVersion,{exact:true}).waitFor();await page.getByText('Полный учебный комплект сохранён:',{exact:false}).waitFor({timeout:90000});await context.setOffline(true);await page.goto(base+'#topic/py-tuples');await page.getByRole('tab',{name:'Практика',exact:true}).click();await page.getByRole('progressbar',{name:'Прогресс практики',exact:true}).waitFor();assert.equal(await page.getByRole('progressbar',{name:'Прогресс мини-теста',exact:true}).count(),0);assert.equal(await count('Контрольных попыток'),'1');assert.equal(await count('Контроль: верно / ошибки'),'0 / 1');assert.equal(await count('Тренировочных ответов'),'0');
 for(const value of ['0',q.answer]){await page.getByLabel('Твой ответ',{exact:true}).fill(value);await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();if(value==='0')await page.getByRole('button',{name:'Попробовать ещё раз',exact:true}).click();}
 await page.getByRole('button',{name:'Завершить практику',exact:true}).click();await page.getByRole('heading',{name:'Практика завершена',exact:true}).waitFor();assert.ok((await page.locator('.quiz-finish').textContent()).includes('не увеличивают контрольные ошибки'));assert.equal(await count('Тренировочных ответов'),'2');assert.equal(await count('Контрольных попыток'),'1');const after=await state();assert.deepEqual(after.attempts,legacy.attempts);assert.deepEqual(after.errors,legacy.errors);assert.deepEqual(after.reviews,legacy.reviews);pass('Practice labels/finish explanation and visible training counter agree with separate statistics; legacy history is unchanged');
 for(const width of [320,360,390,1440]){await page.setViewportSize({width,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('.topic-progress').screenshot({path:'outputs/release034-counters-'+width+'.png'});}pass('Long counter labels fit 320/360/390/desktop without overflow');
 await page.getByRole('tab',{name:'Мини-тест',exact:true}).click();await page.getByRole('progressbar',{name:'Прогресс мини-теста',exact:true}).waitFor();assert.equal(await page.getByRole('button',{name:'Показать подсказку',exact:true}).count(),0);await page.getByRole('radio',{name:'[5]',exact:true}).check();await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();await page.getByRole('button',{name:'Попробовать ещё раз',exact:true}).click();await page.getByRole('radio',{name:'(5,)',exact:true}).check();await page.getByRole('button',{name:'Проверить ответ',exact:true}).click();await page.getByRole('button',{name:'Завершить мини-тест',exact:true}).click();await page.getByRole('heading',{name:'Мини-тест завершён',exact:true}).waitFor();assert.ok((await page.locator('.quiz-finish').textContent()).includes('0 из 1'));assert.equal(await count('Контрольных попыток'),'2');assert.equal(await count('Контроль: верно / ошибки'),'0 / 2');assert.equal(await count('Тренировочных ответов'),'2');pass('Mini-test labels remain distinct and first failed answer is counted once after correction');
 await page.goto(base+'#easy');await page.getByRole('progressbar',{name:'Прогресс повторения',exact:true}).waitFor();assert.equal(await page.getByRole('progressbar',{name:'Прогресс мини-теста',exact:true}).count(),0);pass('Easy review uses repetition labels, not mini-test labels');
 await page.goto(base+'#settings');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Экспортировать JSON',exact:true}).click();const text=fs.readFileSync(await(await download).path(),'utf8');assert.equal(JSON.parse(text).appVersion,appVersion);assert.deepEqual(parseBackup(text).data,await state());assert.equal(external.size,0);assert.deepEqual(errors,[]);pass('Offline release metadata/backup agrees with 0.3.4; no external requests');fs.writeFileSync('outputs/RELEASE034-LABELS.json',JSON.stringify({checks,errors,externalRequests:[...external]},null,2));
}finally{if(context)await context.close();await new Promise(r=>server.close(r));}
