import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {execFileSync} from 'node:child_process';
import {checkContentBank} from '../../scripts/content-bank.mjs';import {emptyState,stats} from '../../src/domain/progress.ts';
import {learningSets,recordTraining,startTopicTest,answerTopicTest,advanceTopicTest} from '../../src/domain/study-flow.ts';
import {serializeBackup,parseBackup,validateStudyState,validateQuestion} from '../../src/domain/backup.ts';
import {outputLines,outputPreview,outputPosition,outputScroll,tracebackSummary} from '../../src/domain/output.ts';import {pythonMismatch} from '../../src/python/assessment.ts';
const {questions:bank}=checkContentBank(),flow=JSON.parse(fs.readFileSync('src/data/study-flow.json')).topics;
const q=bank.find(q=>q.id==='b1-math-06'),now=new Date('2026-10-09T10:00:00Z');
test('All supplied topics have explicit, non-overlapping learning sets; duplicates and equivalent programs stay in practice',()=>{
 assert.equal(Object.keys(flow).length,new Set(bank.filter(q=>!q.easy).map(q=>q.topic)).size);for(const topic of Object.keys(flow)){const sets=learningSets(bank,topic,flow);assert.ok(sets.practice.length);assert.ok(sets.test.length);const ids=[...sets.practice,...sets.test].map(q=>q.id);assert.equal(new Set(ids).size,ids.length);assert.deepEqual([...ids].sort(),bank.filter(q=>q.topic===topic&&!q.easy).map(q=>q.id).sort());assert.ok(sets.test.every(q=>!sets.practice.some(p=>p.prompt===q.prompt&&p.answer===q.answer&&JSON.stringify(p.python)===JSON.stringify(q.python))));}
 assert.ok(flow.unionwords.practice.includes('u4')&&flow.unionwords.practice.includes('b1-russian-16'));assert.ok(flow.binary.practice.includes('b4')&&flow.binary.practice.includes('b1-informatics-04'));assert.ok(flow['py-loops'].practice.includes('b1-python-10')&&flow['py-loops'].practice.includes('b1-python-11'));
 assert.deepEqual(learningSets(bank,'absent',{}),{practice:[],test:[]});assert.throws(()=>learningSets(bank,q.topic,{[q.topic]:{practice:[q.id],test:[q.id]}}));
});
test('Training is durable separate activity and never creates scored attempts, errors or repetition penalties',()=>{let s=emptyState('control');for(let i=0;i<15;i++)s=recordTraining(s,q,'wrong',false,'training-'+i,now);assert.equal(s.training.length,15);assert.equal(s.attempts.length,0);assert.equal(s.errors.length,0);assert.deepEqual(s.reviews,{});assert.equal(stats(s).errors,0);assert.equal(s.topics[q.topic].status,'Изучаю');assert.deepEqual(parseBackup(serializeBackup(s)).data,s);});
test('Mini-test freezes first answer, persists snapshot/current correction, resumes and records only the first independent attempt',()=>{let s=startTopicTest(emptyState('old'),q.topic,[q],'test-1',now);s=answerTopicTest(s,'test-1','wrong',false,'first',now);s=answerTopicTest(s,'test-1',q.answer,true,'correction',now);assert.equal(s.attempts.length,1);assert.equal(s.errors.length,1);assert.equal(s.topicTests[0].items[0].firstCorrect,false);assert.equal(s.topicTests[0].items[0].correct,true);assert.equal(s.topicTests[0].items[0].answer,'wrong');assert.equal(s.topicTests[0].items[0].lastAnswer,q.answer);assert.deepEqual(parseBackup(serializeBackup(s)).data,s);s=advanceTopicTest(s,'test-1',now);assert.ok(s.topicTests[0].completedAt);assert.deepEqual(answerTopicTest(s,'test-1','x',true,'extra',now),s);assert.equal(s.topicTests[0].items[0].question.prompt,q.prompt);});
test('Malformed new backup fields are refused and historical records remain unchanged',()=>{let s=answerTopicTest(startTopicTest(emptyState('old'),q.topic,[q],'test-1',now),'test-1',q.answer,true,'first',now);for(const change of [s=>s.topicTests[0].index=99,s=>s.topicTests[0].items[0].firstCorrect=false,s=>s.topicTests[0].items[0].attemptId='missing',s=>s.topicTests[0].items[0].question.topic='other',s=>s.training=[{...s.attempts[0],context:'practice'}]]){const bad=structuredClone(s);change(bad);assert.throws(()=>validateStudyState(bad));}assert.deepEqual(validateStudyState(s),s);const old=emptyState('legacy');assert.deepEqual(parseBackup(serializeBackup(old)).data,old);old.schemaVersion=1;delete old.adaptive;assert.equal(validateStudyState(old).schemaVersion,2);});
test('All 25 programs preserve canonical conditions, solution, tests, IDs and skills from published 0.3.3; only beginner presentation is added',()=>{for(const subject of ['python','informatics']){const old=JSON.parse(execFileSync('git',['show','69e7b56:src/data/banks/stage3b1-'+subject+'.json'],{encoding:'utf8'}));for(const previous of old.questions){const current=bank.find(q=>q.id===previous.id);if(current.answerType!=='code'){assert.deepEqual(current,previous);continue;}const {presentation,version,...rest}=current;assert.equal(version,3);const {version:oldVersion,...before}=previous;assert.equal(oldVersion,2);assert.deepEqual(rest,before);}}});
test('Presentation schema is bounded and explicit, stdin sum has a 2/3→5 example, all origins remain generated',()=>{const codes=bank.filter(q=>q.id.startsWith('b1-')&&q.answerType==='code');assert.equal(codes.length,25);for(const q of codes){assert.ok(q.presentation.statement);assert.equal(q.origin,'generated');const bad=structuredClone(q);bad.presentation.inputHelp='yes';assert.throws(()=>validateQuestion(bad));}const sum=codes.find(q=>q.id==='b1-python-03');assert.deepEqual(sum.python.visibleTests[0],{stdin:'2\n3',expectedOutput:'5'});assert.ok(sum.presentation.statement.includes('только сумму'));assert.ok(!sum.presentation.statement.includes('−100'));assert.ok(sum.presentation.limits.includes('−100'));});
test('Preview retains raw whitespace/order; full text is never replaced and anchor scales with line height',()=>{const short='  2\n\n  3\n';assert.equal(outputPreview(short),short);const long=Array.from({length:500},(_,i)=>'  '+i).join('\n')+'\n';assert.equal(outputLines(long),500);assert.equal(outputPreview(long),long.split('\n').slice(0,15).join('\n')+'\n');const p=outputPosition(327*24+6,17,24);assert.deepEqual(p,{line:327,fraction:.25,left:17});assert.equal(outputScroll(p,32),327*32+8);assert.equal(outputLines(''),0);});
test('Mismatch feedback distinguishes facts and avoids guessing the user algorithm',()=>{const a={ok:true,stdout:'0\n1\n2\n',stderr:''};assert.ok(pythonMismatch(a,{expectedOutput:'5'}).includes('3 строк вместо 1'));assert.ok(!pythonMismatch(a,{expectedOutput:'5'}).includes('range'));assert.ok(pythonMismatch({...a,stdout:''},{expectedOutput:'5'}).includes('ничего'));assert.ok(pythonMismatch({...a,value:0},{expectedReturn:4},true).includes('return'));for(const kind of ['syntax','runtime','timeout','stopped','infrastructure'])assert.ok(pythonMismatch({...a,kind}));});
test('Long single-line preview is bounded; traceback summary is factual and leaves the original complete string intact',()=>{const text='x'.repeat(6000);assert.equal(outputPreview(text),text.slice(0,3000));const trace='Traceback\n'+('Internal frame\n'.repeat(40))+'  File "<playground.py>", line 7\nZeroDivisionError: division by zero\n';assert.equal(tracebackSummary(trace),'ZeroDivisionError: division by zero · File "<playground.py>", line 7');assert.ok(trace.endsWith('ZeroDivisionError: division by zero\n'));assert.equal(tracebackSummary('nothing'), '');});
